name: Arduino Auto-Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$HOME/bin" >> $GITHUB_PATH
      
      - name: Install Arduino Core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
      
      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn arduino:avr:uno your-sketch.ino
      - name: Upload to Arduino
        run: |
          arduino-cli upload -p COM17 --fqbn arduino:avr:uno your-sketch.ino
